-- Illustrative development reference nutrition; all macros per 100 g of the stated form.
-- Verify against actual packaging for individual tracking. No live prices or user data.
insert into public.foods(name) values('Chicken breast') on conflict(name) do nothing;
update public.foods set category='protein',tags=array['meat']::text[],aliases=array['chicken']::text[],preparation='Raw boneless, skinless' where name='Chicken breast';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,120,22.5,0,2.6,0,170,null,'Development reference estimate; verify packaging' from public.foods where name='Chicken breast';
insert into public.foods(name) values('Chicken thighs') on conflict(name) do nothing;
update public.foods set category='protein',tags=array['meat']::text[],aliases=array['chicken']::text[],preparation='Raw boneless, skinless' where name='Chicken thighs';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,144,19.7,0,6.3,0,170,null,'Development reference estimate; verify packaging' from public.foods where name='Chicken thighs';
insert into public.foods(name) values('Ground turkey') on conflict(name) do nothing;
update public.foods set category='protein',tags=array['meat']::text[],aliases=array['lean ground turkey']::text[],preparation='Raw, approximately 93% lean' where name='Ground turkey';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,172,21.4,0,9.4,0,170,null,'Development reference estimate; verify packaging' from public.foods where name='Ground turkey';
insert into public.foods(name) values('Lean beef') on conflict(name) do nothing;
update public.foods set category='premium-protein',tags=array['meat']::text[],aliases=array['beef']::text[],preparation='Raw, lean' where name='Lean beef';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,172,21,0,9,0,170,null,'Development reference estimate; verify packaging' from public.foods where name='Lean beef';
insert into public.foods(name) values('Eggs') on conflict(name) do nothing;
update public.foods set category='protein',tags=array['egg']::text[],aliases=array['egg']::text[],preparation='Raw edible portion; one large egg ≈ 50 g' where name='Eggs';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,143,12.6,0.7,9.5,0,50,50,'Development reference estimate; verify packaging' from public.foods where name='Eggs';
insert into public.foods(name) values('Egg whites') on conflict(name) do nothing;
update public.foods set category='protein',tags=array['egg']::text[],aliases=array['egg white','eggs']::text[],preparation='Liquid, uncooked' where name='Egg whites';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,52,10.9,0.7,0.2,0,100,null,'Development reference estimate; verify packaging' from public.foods where name='Egg whites';
insert into public.foods(name) values('Greek yogurt') on conflict(name) do nothing;
update public.foods set category='protein',tags=array['dairy']::text[],aliases=array['yogurt']::text[],preparation='Plain nonfat' where name='Greek yogurt';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,59,10.3,3.6,0.4,0,170,null,'Development reference estimate; verify packaging' from public.foods where name='Greek yogurt';
insert into public.foods(name) values('Cottage cheese') on conflict(name) do nothing;
update public.foods set category='protein',tags=array['dairy']::text[],aliases=array['cheese']::text[],preparation='Low fat' where name='Cottage cheese';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,82,11.1,3.4,2.3,0,150,null,'Development reference estimate; verify packaging' from public.foods where name='Cottage cheese';
insert into public.foods(name) values('Tuna') on conflict(name) do nothing;
update public.foods set category='protein',tags=array['fish']::text[],aliases=array['fish']::text[],preparation='Canned in water, drained' where name='Tuna';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,116,25.5,0,0.8,0,100,null,'Development reference estimate; verify packaging' from public.foods where name='Tuna';
insert into public.foods(name) values('Salmon') on conflict(name) do nothing;
update public.foods set category='premium-protein',tags=array['fish']::text[],aliases=array['fish']::text[],preparation='Raw' where name='Salmon';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,208,20,0,13,0,170,null,'Development reference estimate; verify packaging' from public.foods where name='Salmon';
insert into public.foods(name) values('Tofu') on conflict(name) do nothing;
update public.foods set category='protein',tags=array['vegan','soy']::text[],aliases=array['soy']::text[],preparation='Firm, drained' where name='Tofu';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,144,17.3,2.8,8.7,2.3,170,null,'Development reference estimate; verify packaging' from public.foods where name='Tofu';
insert into public.foods(name) values('Beans') on conflict(name) do nothing;
update public.foods set category='protein',tags=array['vegan']::text[],aliases=array['black beans','kidney beans']::text[],preparation='Cooked or canned, drained' where name='Beans';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,127,8.7,22.8,0.5,6.4,150,null,'Development reference estimate; verify packaging' from public.foods where name='Beans';
insert into public.foods(name) values('Protein powder') on conflict(name) do nothing;
update public.foods set category='protein',tags=array['dairy']::text[],aliases=array['whey','whey protein']::text[],preparation='Whey powder; check your product label' where name='Protein powder';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,400,80,8,5,0,30,null,'Development reference estimate; verify packaging' from public.foods where name='Protein powder';
insert into public.foods(name) values('Rice') on conflict(name) do nothing;
update public.foods set category='carb',tags=array['vegan']::text[],aliases=array['jasmine rice','white rice']::text[],preparation='Dry, uncooked' where name='Rice';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,365,7.1,80,0.7,1.3,70,null,'Development reference estimate; verify packaging' from public.foods where name='Rice';
insert into public.foods(name) values('Oats') on conflict(name) do nothing;
update public.foods set category='carb',tags=array['vegan','gluten']::text[],aliases=array['oatmeal']::text[],preparation='Dry rolled oats; not certified gluten-free' where name='Oats';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,389,16.9,66.3,6.9,10.6,60,null,'Development reference estimate; verify packaging' from public.foods where name='Oats';
insert into public.foods(name) values('Potatoes') on conflict(name) do nothing;
update public.foods set category='carb',tags=array['vegan']::text[],aliases=array['potato']::text[],preparation='Raw with skin' where name='Potatoes';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,77,2,17.5,0.1,2.2,250,null,'Development reference estimate; verify packaging' from public.foods where name='Potatoes';
insert into public.foods(name) values('Sweet potatoes') on conflict(name) do nothing;
update public.foods set category='carb',tags=array['vegan']::text[],aliases=array['sweet potato']::text[],preparation='Raw with skin' where name='Sweet potatoes';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,86,1.6,20.1,0.1,3,250,null,'Development reference estimate; verify packaging' from public.foods where name='Sweet potatoes';
insert into public.foods(name) values('Bread') on conflict(name) do nothing;
update public.foods set category='carb',tags=array['vegan','gluten']::text[],aliases=array['whole grain bread','whole-grain bread','wheat']::text[],preparation='Whole-grain bread; approximate 40 g slice' where name='Bread';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,247,13,41,4.2,7,40,40,'Development reference estimate; verify packaging' from public.foods where name='Bread';
insert into public.foods(name) values('Pasta') on conflict(name) do nothing;
update public.foods set category='carb',tags=array['vegan','gluten']::text[],aliases=array['wheat']::text[],preparation='Dry' where name='Pasta';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,371,13,75,1.5,3.2,75,null,'Development reference estimate; verify packaging' from public.foods where name='Pasta';
insert into public.foods(name) values('Tortillas') on conflict(name) do nothing;
update public.foods set category='carb',tags=array['vegan','gluten']::text[],aliases=array['wheat']::text[],preparation='Flour tortilla; approximate 45 g piece' where name='Tortillas';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,312,8,52,8,3.3,45,45,'Development reference estimate; verify packaging' from public.foods where name='Tortillas';
insert into public.foods(name) values('Quinoa') on conflict(name) do nothing;
update public.foods set category='carb',tags=array['vegan']::text[],aliases=array[]::text[],preparation='Dry' where name='Quinoa';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,368,14.1,64.2,6.1,7,60,null,'Development reference estimate; verify packaging' from public.foods where name='Quinoa';
insert into public.foods(name) values('Broccoli') on conflict(name) do nothing;
update public.foods set category='fiber',tags=array['vegan']::text[],aliases=array[]::text[],preparation='Raw or frozen, unprepared' where name='Broccoli';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,34,2.8,6.6,0.4,2.6,150,null,'Development reference estimate; verify packaging' from public.foods where name='Broccoli';
insert into public.foods(name) values('Spinach') on conflict(name) do nothing;
update public.foods set category='fiber',tags=array['vegan']::text[],aliases=array[]::text[],preparation='Raw' where name='Spinach';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,23,2.9,3.6,0.4,2.2,100,null,'Development reference estimate; verify packaging' from public.foods where name='Spinach';
insert into public.foods(name) values('Mixed vegetables') on conflict(name) do nothing;
update public.foods set category='fiber',tags=array['vegan']::text[],aliases=array['frozen vegetables']::text[],preparation='Frozen, unprepared' where name='Mixed vegetables';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,65,3,12,0.6,4,150,null,'Development reference estimate; verify packaging' from public.foods where name='Mixed vegetables';
insert into public.foods(name) values('Carrots') on conflict(name) do nothing;
update public.foods set category='fiber',tags=array['vegan']::text[],aliases=array[]::text[],preparation='Raw' where name='Carrots';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,41,0.9,9.6,0.2,2.8,100,null,'Development reference estimate; verify packaging' from public.foods where name='Carrots';
insert into public.foods(name) values('Bell peppers') on conflict(name) do nothing;
update public.foods set category='fiber',tags=array['vegan']::text[],aliases=array['pepper']::text[],preparation='Raw' where name='Bell peppers';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,31,1,6,0.3,2.1,100,null,'Development reference estimate; verify packaging' from public.foods where name='Bell peppers';
insert into public.foods(name) values('Green beans') on conflict(name) do nothing;
update public.foods set category='fiber',tags=array['vegan']::text[],aliases=array[]::text[],preparation='Raw' where name='Green beans';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,31,1.8,7,0.2,2.7,150,null,'Development reference estimate; verify packaging' from public.foods where name='Green beans';
insert into public.foods(name) values('Berries') on conflict(name) do nothing;
update public.foods set category='fiber',tags=array['vegan']::text[],aliases=array[]::text[],preparation='Mixed, fresh or frozen' where name='Berries';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,50,0.8,12,0.4,3,100,null,'Development reference estimate; verify packaging' from public.foods where name='Berries';
insert into public.foods(name) values('Blueberries') on conflict(name) do nothing;
update public.foods set category='fiber',tags=array['vegan']::text[],aliases=array['berries']::text[],preparation='Fresh or frozen' where name='Blueberries';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,57,0.7,14.5,0.3,2.4,100,null,'Development reference estimate; verify packaging' from public.foods where name='Blueberries';
insert into public.foods(name) values('Bananas') on conflict(name) do nothing;
update public.foods set category='fiber',tags=array['vegan']::text[],aliases=array['banana']::text[],preparation='Edible portion without peel' where name='Bananas';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,89,1.1,22.8,0.3,2.6,118,118,'Development reference estimate; verify packaging' from public.foods where name='Bananas';
insert into public.foods(name) values('Apples') on conflict(name) do nothing;
update public.foods set category='fiber',tags=array['vegan']::text[],aliases=array['apple']::text[],preparation='With skin, without core' where name='Apples';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,52,0.3,13.8,0.2,2.4,182,182,'Development reference estimate; verify packaging' from public.foods where name='Apples';
insert into public.foods(name) values('Lentils') on conflict(name) do nothing;
update public.foods set category='protein',tags=array['vegan']::text[],aliases=array[]::text[],preparation='Cooked or canned, drained' where name='Lentils';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,116,9,20,0.4,7.9,150,null,'Development reference estimate; verify packaging' from public.foods where name='Lentils';
insert into public.foods(name) values('Chia seeds') on conflict(name) do nothing;
update public.foods set category='fiber',tags=array['vegan']::text[],aliases=array['chia']::text[],preparation='Dry' where name='Chia seeds';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,486,16.5,42.1,30.7,34.4,15,null,'Development reference estimate; verify packaging' from public.foods where name='Chia seeds';
insert into public.foods(name) values('Peanut butter') on conflict(name) do nothing;
update public.foods set category='fat',tags=array['vegan','peanut']::text[],aliases=array['peanuts','peanut']::text[],preparation='Smooth' where name='Peanut butter';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,588,25,20,50,6,20,null,'Development reference estimate; verify packaging' from public.foods where name='Peanut butter';
insert into public.foods(name) values('Avocado') on conflict(name) do nothing;
update public.foods set category='fat',tags=array['vegan']::text[],aliases=array[]::text[],preparation='Edible flesh' where name='Avocado';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,160,2,8.5,14.7,6.7,80,null,'Development reference estimate; verify packaging' from public.foods where name='Avocado';
insert into public.foods(name) values('Olive oil') on conflict(name) do nothing;
update public.foods set category='fat',tags=array['vegan']::text[],aliases=array['oil']::text[],preparation='Oil by weight' where name='Olive oil';
insert into public.food_nutrition(food_id,calories,protein,carbs,fat,fiber,serving_g,piece_g,source) select id,884,0,0,100,0,10,null,'Development reference estimate; verify packaging' from public.foods where name='Olive oil';
insert into public.meals(id,slug,name,slots,instructions,cooking_minutes,complexity,batch_friendly) values('40000000-0000-4000-8000-000000000001','yogurt-oats','Greek yogurt oat bowl',array['Breakfast','Snack']::text[],array['Stir yogurt, dry oats, and chia together. Add a splash of water if needed.','Top with blueberries. Eat immediately or refrigerate overnight.']::text[],5,1,false);
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000001',id,250,'protein' from public.foods where name='Greek yogurt';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000001',id,60,'carb' from public.foods where name='Oats';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000001',id,100,'fiber' from public.foods where name='Blueberries';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000001',id,15,'fiber' from public.foods where name='Chia seeds';
insert into public.meals(id,slug,name,slots,instructions,cooking_minutes,complexity,batch_friendly) values('40000000-0000-4000-8000-000000000002','egg-oats','Eggs & warm oats',array['Breakfast']::text[],array['Cook oats with water; serve with chopped apple.','Scramble the egg and egg whites in a nonstick pan until fully set.']::text[],10,1,false);
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000002',id,100,'protein' from public.foods where name='Eggs';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000002',id,150,'protein' from public.foods where name='Egg whites';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000002',id,60,'carb' from public.foods where name='Oats';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000002',id,120,'fiber' from public.foods where name='Apples';
insert into public.meals(id,slug,name,slots,instructions,cooking_minutes,complexity,batch_friendly) values('40000000-0000-4000-8000-000000000003','tofu-potatoes','Tofu potato skillet',array['Breakfast','Lunch','Dinner']::text[],array['Dice the raw potato and microwave with a little water until tender.','Heat oil in a pan. Add tofu, potatoes, and spinach; cook until hot. Season to taste.']::text[],20,1,true);
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000003',id,180,'protein' from public.foods where name='Tofu';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000003',id,250,'carb' from public.foods where name='Potatoes';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000003',id,100,'fiber' from public.foods where name='Spinach';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000003',id,8,'fat' from public.foods where name='Olive oil';
insert into public.meals(id,slug,name,slots,instructions,cooking_minutes,complexity,batch_friendly) values('40000000-0000-4000-8000-000000000004','chicken-rice','Chicken rice bowl',array['Lunch','Dinner']::text[],array['Cook the weighed dry rice with water according to its package.','Cook chicken thoroughly. Steam broccoli and finish with the measured oil. Divide into portions.']::text[],30,2,true);
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000004',id,180,'protein' from public.foods where name='Chicken breast';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000004',id,75,'carb' from public.foods where name='Rice';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000004',id,180,'fiber' from public.foods where name='Broccoli';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000004',id,10,'fat' from public.foods where name='Olive oil';
insert into public.meals(id,slug,name,slots,instructions,cooking_minutes,complexity,batch_friendly) values('40000000-0000-4000-8000-000000000005','turkey-potatoes','Turkey & sweet potato bowl',array['Lunch','Dinner']::text[],array['Dice and roast the sweet potato with the measured oil.','Brown turkey until thoroughly cooked, heat vegetables, and assemble.']::text[],30,2,true);
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000005',id,170,'protein' from public.foods where name='Ground turkey';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000005',id,250,'carb' from public.foods where name='Sweet potatoes';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000005',id,150,'fiber' from public.foods where name='Mixed vegetables';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000005',id,5,'fat' from public.foods where name='Olive oil';
insert into public.meals(id,slug,name,slots,instructions,cooking_minutes,complexity,batch_friendly) values('40000000-0000-4000-8000-000000000006','tuna-bean','Tuna & white bean plate',array['Lunch','Dinner']::text[],array['Drain the tuna and beans. Rinse the spinach.','Combine, dress with the measured oil, and season.']::text[],10,1,false);
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000006',id,140,'protein' from public.foods where name='Tuna';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000006',id,180,'protein' from public.foods where name='Beans';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000006',id,70,'fiber' from public.foods where name='Spinach';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000006',id,10,'fat' from public.foods where name='Olive oil';
insert into public.meals(id,slug,name,slots,instructions,cooking_minutes,complexity,batch_friendly) values('40000000-0000-4000-8000-000000000007','lentil-rice','Lentil rice & greens',array['Breakfast','Lunch','Dinner']::text[],array['Cook the dry rice in water according to its package.','Warm the cooked lentils with spinach and measured oil. Serve over rice.']::text[],20,1,true);
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000007',id,200,'protein' from public.foods where name='Lentils';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000007',id,65,'carb' from public.foods where name='Rice';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000007',id,100,'fiber' from public.foods where name='Spinach';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000007',id,10,'fat' from public.foods where name='Olive oil';
insert into public.meals(id,slug,name,slots,instructions,cooking_minutes,complexity,batch_friendly) values('40000000-0000-4000-8000-000000000008','tofu-rice','Tofu & broccoli bowl',array['Lunch','Dinner']::text[],array['Cook the weighed dry rice with water.','Pan-cook the tofu with oil. Steam broccoli and assemble.']::text[],20,1,true);
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000008',id,200,'protein' from public.foods where name='Tofu';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000008',id,70,'carb' from public.foods where name='Rice';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000008',id,180,'fiber' from public.foods where name='Broccoli';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000008',id,8,'fat' from public.foods where name='Olive oil';
insert into public.meals(id,slug,name,slots,instructions,cooking_minutes,complexity,batch_friendly) values('40000000-0000-4000-8000-000000000009','cottage-fruit','Cottage cheese & fruit',array['Breakfast','Snack']::text[],array['Spoon cottage cheese into a bowl. Add sliced banana and chia seeds.']::text[],5,1,false);
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000009',id,250,'protein' from public.foods where name='Cottage cheese';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000009',id,118,'carb' from public.foods where name='Bananas';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000009',id,15,'fiber' from public.foods where name='Chia seeds';
insert into public.meals(id,slug,name,slots,instructions,cooking_minutes,complexity,batch_friendly) values('40000000-0000-4000-8000-000000000010','bean-avocado','Bean & avocado bowl',array['Lunch','Dinner','Snack']::text[],array['Warm the drained beans and frozen vegetables.','Top with diced avocado and season to taste.']::text[],10,1,false);
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000010',id,200,'protein' from public.foods where name='Beans';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000010',id,80,'fat' from public.foods where name='Avocado';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000010',id,150,'fiber' from public.foods where name='Mixed vegetables';
insert into public.meals(id,slug,name,slots,instructions,cooking_minutes,complexity,batch_friendly) values('40000000-0000-4000-8000-000000000011','peanut-oats','Banana peanut oats',array['Breakfast','Snack']::text[],array['Cook the dry oats in water.','Stir in peanut butter and chia. Top with banana.']::text[],10,1,true);
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000011',id,70,'carb' from public.foods where name='Oats';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000011',id,25,'fat' from public.foods where name='Peanut butter';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000011',id,118,'carb' from public.foods where name='Bananas';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000011',id,15,'fiber' from public.foods where name='Chia seeds';
insert into public.meals(id,slug,name,slots,instructions,cooking_minutes,complexity,batch_friendly) values('40000000-0000-4000-8000-000000000012','tofu-berry','Tofu berry chia bowl',array['Breakfast','Snack']::text[],array['Blend the tofu with berries and banana until smooth.','Stir in chia and refrigerate until ready to eat.']::text[],5,1,false);
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000012',id,180,'protein' from public.foods where name='Tofu';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000012',id,120,'fiber' from public.foods where name='Blueberries';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000012',id,15,'fiber' from public.foods where name='Chia seeds';
insert into public.meal_items(meal_id,food_id,quantity_g,role) select '40000000-0000-4000-8000-000000000012',id,100,'carb' from public.foods where name='Bananas';
